from .lattice import (
    AtomState,
    DetectorResult,
    IListResult,
    MeasureFuture,
    MeasureResult,
    ObservableResult,
    TupleResult,
    Value,
)

class _ElemVisitor:
    def is_subseteq_Value(self, elem: Value) -> bool: ...
    def is_subseteq_AtomState(self, elem: AtomState) -> bool: ...
    def is_subseteq_MeasureFuture(self, elem: MeasureFuture) -> bool: ...
    def is_subseteq_MeasureResult(self, elem: MeasureResult) -> bool: ...
    def is_subseteq_IListResult(self, elem: IListResult) -> bool: ...
    def is_subseteq_TupleResult(self, elem: "TupleResult") -> bool: ...
    def is_subseteq_DetectorResult(self, elem: "DetectorResult") -> bool: ...
    def is_subseteq_ObservableResult(self, elem: "ObservableResult") -> bool: ...
